// Generated by CoffeeScript 1.3.3
var Alt, AltCommand, Command, CommandFactory, Config, Diagram, ElseCommand, EndCommand, Execution, ExecutionCommand, ExecutionEnd, ExecutionStart, Fragment, FragmentBase, Guard, Item, LifeLine, Message, MessageCommand, Note, NoteCommand, OptionCommand, ReplyMessage, SequenceCommandParser, SequenceDiagram, State, SyncMessage, Util, View, ViewGroup,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Util = {
  measureTextHeight: function() {
    var body;
    if (!this.span) {
      this.span = document.createElement("span");
      this.span.textContent = "gM";
      this.span.style.visibility = "hidden";
      this.span.style.position = "absolute";
      body = document.body;
      body.insertBefore(this.span, body.firstChild);
    }
    return this.span.offsetHeight / 2;
  },
  S4: function() {
    return (((1 + Math.random()) * 0x10000) | 0).toString(16).substring(1);
  },
  guid: function() {
    var S4;
    S4 = this.S4;
    return S4() + S4() + "-" + S4() + "-" + S4() + "-" + S4() + "-" + S4() + S4() + S4();
  },
  trim: function(text) {
    return text.replace(/^\s+|\s+$/g, "");
  }
};

Config = {
  margin: 8,
  itemMargin: 20,
  lineMinWidth: 64,
  lineHeight: 32,
  padding: 4,
  executionWidth: 8,
  arrowSize: 8,
  curveWidth: 12,
  fragmentMargin: 5,
  textStyle: 'rgb(0, 0, 0)',
  strokeStyle: 'rgb(0, 0, 0)',
  fillStyle: 'rgb(255, 255, 255)',
  textFillStyle: 'rgba(255, 255, 255, 0.8)'
};

View = (function() {

  function View() {
    this.x = 0;
    this.y = 0;
  }

  View.prototype.draw = function(context) {
    context.save();
    this.translate(context);
    this.onDraw(context);
    this.dispatchDraw(context);
    return context.restore();
  };

  View.prototype.translate = function(context) {
    return context.translate(this.x, this.y);
  };

  View.prototype.onDraw = function(context) {};

  View.prototype.dispatchDraw = function(context) {};

  return View;

})();

ViewGroup = (function(_super) {

  __extends(ViewGroup, _super);

  function ViewGroup() {
    ViewGroup.__super__.constructor.call(this);
    this.children = [];
  }

  ViewGroup.prototype.dispatchDraw = function(context) {
    var child, _i, _len, _ref, _results;
    _ref = this.children;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      child = _ref[_i];
      _results.push(child.draw(context));
    }
    return _results;
  };

  ViewGroup.prototype.add = function(child) {
    return this.children.push(child);
  };

  return ViewGroup;

})(View);

Diagram = (function(_super) {

  __extends(Diagram, _super);

  function Diagram(context) {
    this.context = context;
    Diagram.__super__.constructor.call(this);
  }

  Diagram.prototype.measureTextWidth = function(text) {
    return this.context.measureText(text).width;
  };

  Diagram.prototype.show = function() {
    this.layout();
    this.context.save();
    this.context.translate(0.5, 0.5);
    this.draw(this.context);
    return this.context.restore();
  };

  Diagram.prototype.layout = function() {};

  return Diagram;

})(ViewGroup);

SequenceDiagram = (function(_super) {

  __extends(SequenceDiagram, _super);

  function SequenceDiagram(context) {
    SequenceDiagram.__super__.constructor.call(this, context);
    this.lines = [];
    this.items = [];
    this.fragmentStack = [];
    this.fragmentMaxStack = 0;
    this.x = Config.margin;
    this.y = Config.margin;
    this.bottom = 0;
    this.right = 0;
  }

  SequenceDiagram.prototype.layout = function() {
    this.layoutLifeLines();
    return this.layoutItems();
  };

  SequenceDiagram.prototype.layoutLifeLines = function() {
    var line, right, _i, _len, _ref, _results;
    right = 0;
    _ref = this.lines;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      line = _ref[_i];
      line.layout(right);
      _results.push(right += line.width + Config.margin);
    }
    return _results;
  };

  SequenceDiagram.prototype.layoutItems = function() {
    var bottom, item, last, lineMargin, _i, _len, _ref;
    bottom = Config.lineHeight;
    _ref = this.items;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      item.y = bottom + Config.itemMargin;
      item.layout();
      bottom = item.bottom;
    }
    this.bottom = bottom + Config.itemMargin;
    lineMargin = this.fragmentMaxStack * Config.fragmentMargin;
    this.shiftLifeLine(lineMargin);
    if (this.lines.length === 0) {
      return;
    }
    last = this.lines[this.lines.length - 1];
    return this.right = last.x + last.width + lineMargin;
  };

  SequenceDiagram.prototype.addLine = function(lifeLine) {
    this.lines.push(lifeLine);
    return this.add(lifeLine);
  };

  SequenceDiagram.prototype.addItem = function(item) {
    this.items.push(item);
    return this.add(item);
  };

  SequenceDiagram.prototype.pushFragment = function(fragment) {
    this.fragmentStack.push(fragment);
    return this.fragmentMaxStack = Math.max(this.fragmentMaxStack, this.fragmentStack.length);
  };

  SequenceDiagram.prototype.popFragment = function() {
    return this.fragmentStack.pop();
  };

  SequenceDiagram.prototype.shiftLifeLine = function(shiftValue) {
    var line, _i, _len, _ref, _results;
    _ref = this.lines;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      line = _ref[_i];
      _results.push(line.x += shiftValue);
    }
    return _results;
  };

  return SequenceDiagram;

})(Diagram);

LifeLine = (function(_super) {

  __extends(LifeLine, _super);

  function LifeLine(diagram, name) {
    this.diagram = diagram;
    this.name = name;
    LifeLine.__super__.constructor.call(this);
    this.position = 0;
    this.stack = [];
  }

  LifeLine.prototype.measureWidth = function() {
    this.textWidth = this.diagram.measureTextWidth(this.name);
    return this.width = Math.max(this.textWidth + Config.padding * 2, Config.lineMinWidth);
  };

  LifeLine.prototype.onDraw = function(context) {
    context.strokeRect(-this.width / 2, 0, this.width, Config.lineHeight);
    context.fillText(this.name, -this.textWidth / 2, Config.lineHeight / 2 + Util.measureTextHeight() / 2);
    context.beginPath();
    context.moveTo(0, Config.lineHeight);
    context.lineTo(0, this.end || this.diagram.bottom);
    return context.stroke();
  };

  LifeLine.prototype.startExecution = function(message) {
    var execution;
    execution = new Execution(this.diagram, this.stack.length);
    execution.start = message;
    this.stack.push(execution);
    execution.parent = this;
    return this.add(execution);
  };

  LifeLine.prototype.endExecution = function(message) {
    var execution;
    execution = this.stack.pop();
    return execution.end = message;
  };

  LifeLine.prototype.currentExecution = function() {
    if (this.stack.length === 0) {
      return null;
    } else {
      return this.stack[this.stack.length - 1];
    }
  };

  LifeLine.prototype.layout = function(current) {
    this.measureWidth();
    return this.x = current + this.width / 2;
  };

  return LifeLine;

})(ViewGroup);

Item = (function(_super) {

  __extends(Item, _super);

  function Item() {
    return Item.__super__.constructor.apply(this, arguments);
  }

  Item.prototype.layout = function() {
    return this.bottom = this.y;
  };

  Item.prototype.getAbsoluteBottom = function() {
    var parent;
    parent = this.parent != null ? this.parent.getAbsoluteTop() : 0;
    return this.bottom + parent;
  };

  Item.prototype.getAbsoluteTop = function() {
    var parent;
    parent = this.parent != null ? this.parent.getAbsoluteTop() : 0;
    return this.y + parent;
  };

  return Item;

})(ViewGroup);

Message = (function(_super) {

  __extends(Message, _super);

  function Message(diagram, text, from, to) {
    this.diagram = diagram;
    this.text = text;
    this.from = from;
    this.to = to;
    Message.__super__.constructor.call(this);
    this.textWidth = this.diagram.measureTextWidth(this.text);
  }

  Message.prototype.onDraw = function(context) {
    var from, to;
    from = this.from.x;
    to = this.to.x;
    if (this.fromAdjust != null) {
      from = from + this.fromAdjust;
    }
    if (this.toAdjust != null) {
      to = to + this.toAdjust;
    }
    if (this.from === this.to) {
      this.drawCurveArrow(context, from, to);
      this.drawCurveText(context, from);
      return;
    }
    this.toRight = from < to;
    this.drawArrow(context, from, to);
    if (this.text != null) {
      return this.drawText(context, from, to);
    }
  };

  Message.prototype.drawArrow = function(context, from, to) {
    var arrowSize, wingTailX, wingTailY;
    arrowSize = Config.arrowSize;
    wingTailX = to - arrowSize * (this.toRight ? 1 : -1);
    wingTailY = arrowSize / 2;
    context.beginPath();
    context.moveTo(from, 0);
    context.lineTo(to, 0);
    context.moveTo(wingTailX, wingTailY);
    context.lineTo(to, 0);
    context.lineTo(wingTailX, -wingTailY);
    return context.stroke();
  };

  Message.prototype.drawCurveArrow = function(context, from, to) {
    var arrowSize, right, wingTailX, wingTailY;
    arrowSize = Config.arrowSize;
    wingTailX = to + arrowSize;
    wingTailY = arrowSize / 2;
    right = Math.min(from, to) + Config.curveWidth * 2;
    context.beginPath();
    context.moveTo(from, 0);
    context.lineTo(right, 0);
    context.lineTo(right, Config.curveWidth);
    context.lineTo(to, Config.curveWidth);
    context.moveTo(wingTailX, Config.curveWidth + wingTailY);
    context.lineTo(to, Config.curveWidth);
    context.lineTo(wingTailX, Config.curveWidth - wingTailY);
    return context.stroke();
  };

  Message.prototype.drawText = function(context, from, to) {
    var base, textHeight;
    base = this.toRight ? from : to;
    context.fillStyle = Config.textFillStyle;
    textHeight = Util.measureTextHeight();
    context.fillRect(base + Math.abs(to - from) / 2 - this.textWidth / 2 - 2, -textHeight - 1, this.textWidth + 3, textHeight);
    context.fillStyle = Config.textStyle;
    return context.fillText(this.text, base + Math.abs(to - from) / 2 - this.textWidth / 2, -3);
  };

  Message.prototype.drawCurveText = function(context, from) {
    var textHeight;
    context.fillStyle = Config.textFillStyle;
    textHeight = Util.measureTextHeight();
    context.fillRect(from + 5, -textHeight - 1, this.textWidth + 3, textHeight);
    context.fillStyle = Config.textStyle;
    return context.fillText(this.text, from + 5, -3);
  };

  Message.prototype.layout = function() {
    this.execution();
    return this.bottom = this.from === this.to ? this.y + Config.curveWidth : this.y;
  };

  Message.prototype.execution = function() {
    this.adjustFrom();
    return this.adjustTo();
  };

  Message.prototype.adjustFrom = function() {
    var from, to, _ref, _ref1, _ref2;
    if (this.from === this.to) {
      this.fromAdjust = (_ref = this.from.currentExecution()) != null ? _ref.right() : void 0;
      return;
    }
    from = this.from.x;
    to = this.to.x;
    if (0 < to - from) {
      return this.fromAdjust = (_ref1 = this.from.currentExecution()) != null ? _ref1.right() : void 0;
    } else {
      return this.fromAdjust = (_ref2 = this.from.currentExecution()) != null ? _ref2.left() : void 0;
    }
  };

  Message.prototype.adjustTo = function() {
    var from, to, _ref, _ref1, _ref2;
    if (this.from === this.to) {
      this.toAdjust = (_ref = this.from.currentExecution()) != null ? _ref.right() : void 0;
      return;
    }
    from = this.from.x;
    to = this.to.x;
    if (0 < to - from) {
      return this.toAdjust = (_ref1 = this.to.currentExecution()) != null ? _ref1.left() : void 0;
    } else {
      return this.toAdjust = (_ref2 = this.to.currentExecution()) != null ? _ref2.right() : void 0;
    }
  };

  return Message;

})(Item);

SyncMessage = (function(_super) {

  __extends(SyncMessage, _super);

  function SyncMessage(diagram, text, from, to) {
    SyncMessage.__super__.constructor.call(this, diagram, text, from, to);
  }

  SyncMessage.prototype.execution = function() {
    this.adjustFrom();
    this.to.startExecution(this);
    return this.adjustTo();
  };

  return SyncMessage;

})(Message);

ReplyMessage = (function(_super) {

  __extends(ReplyMessage, _super);

  function ReplyMessage(diagram, text, from, to) {
    ReplyMessage.__super__.constructor.call(this, diagram, text, from, to);
  }

  ReplyMessage.prototype.execution = function() {
    this.adjustFrom();
    this.from.endExecution(this);
    return this.adjustTo();
  };

  return ReplyMessage;

})(Message);

Execution = (function(_super) {

  __extends(Execution, _super);

  function Execution(diagram, overlap) {
    this.diagram = diagram;
    this.overlap = overlap;
    Execution.__super__.constructor.call(this);
    this.start = null;
    this.end = null;
  }

  Execution.prototype.onDraw = function(context) {
    var end, left, _ref;
    context.strokeStyle = Config.strokeStyle;
    context.fillStyle = Config.fillStyle;
    context.beginPath();
    left = -Config.executionWidth / 2 + Config.executionWidth * this.overlap;
    end = ((_ref = this.end) != null ? _ref.getAbsoluteTop() : void 0) || this.diagram.bottom;
    context.rect(left, this.start.getAbsoluteBottom(), Config.executionWidth, end - this.start.getAbsoluteBottom());
    context.fill();
    return context.stroke();
  };

  Execution.prototype.left = function() {
    return -Config.executionWidth / 2 + Config.executionWidth * this.overlap;
  };

  Execution.prototype.right = function() {
    return Config.executionWidth / 2 + Config.executionWidth * this.overlap;
  };

  return Execution;

})(View);

ExecutionStart = (function(_super) {

  __extends(ExecutionStart, _super);

  function ExecutionStart(target) {
    this.target = target;
    ExecutionStart.__super__.constructor.call(this);
  }

  ExecutionStart.prototype.layout = function() {
    ExecutionStart.__super__.layout.call(this);
    return this.execution();
  };

  ExecutionStart.prototype.execution = function() {
    return this.target.startExecution(this);
  };

  return ExecutionStart;

})(Item);

ExecutionEnd = (function(_super) {

  __extends(ExecutionEnd, _super);

  function ExecutionEnd(target) {
    this.target = target;
    ExecutionEnd.__super__.constructor.call(this);
  }

  ExecutionEnd.prototype.layout = function() {
    ExecutionEnd.__super__.layout.call(this);
    return this.execution();
  };

  ExecutionEnd.prototype.execution = function() {
    return this.target.endExecution(this);
  };

  return ExecutionEnd;

})(Item);

Note = (function(_super) {

  __extends(Note, _super);

  function Note(diagram, text, target, isLeft) {
    this.diagram = diagram;
    this.text = text;
    this.target = target;
    this.isLeft = isLeft;
    Note.__super__.constructor.call(this);
    this.textWidth = this.diagram.measureTextWidth(this.text);
    this.adjustPosition = 0;
  }

  Note.prototype.onDraw = function(context) {
    var left, textBoxHeight, textBoxWidth, textHeight;
    textHeight = Util.measureTextHeight();
    textBoxWidth = this.textWidth + Config.padding * 2;
    textBoxHeight = textHeight + Config.padding * 2;
    if (this.isLeft) {
      left = this.target.x - this.adjustPosition - textBoxWidth - Config.padding;
    } else {
      left = this.target.x + this.adjustPosition + Config.padding;
    }
    context.strokeStyle = Config.strokeStyle;
    context.fillStyle = Config.textFillStyle;
    context.beginPath();
    context.rect(left, 0, textBoxWidth, textBoxHeight);
    context.fill();
    context.stroke();
    context.fillStyle = Config.textStyle;
    return context.fillText(this.text, left + Config.padding, textHeight + Config.padding);
  };

  Note.prototype.adjust = function() {
    var current;
    if (this.isLeft) {
      if (this.target.currentExecution()) {
        return this.adjustPosition += Config.executionWidth / 2;
      }
    } else {
      current = this.target.currentExecution();
      if (current) {
        return this.adjustPosition = current.right();
      }
    }
  };

  Note.prototype.layout = function() {
    this.adjust();
    return this.bottom = this.y + Util.measureTextHeight() + Config.padding * 2;
  };

  return Note;

})(Item);

Alt = (function(_super) {

  __extends(Alt, _super);

  function Alt(diagram, text) {
    this.diagram = diagram;
    this.text = text;
    Alt.__super__.constructor.call(this);
    this.textWidth = this.diagram.measureTextWidth(this.text);
    this.textBoxWidth = this.textWidth + Config.padding * 2;
  }

  Alt.prototype.layout = function() {
    var current, item, _i, _len, _ref;
    current = 0;
    this.margin = this.diagram.fragmentStack.length * Config.fragmentMargin;
    this.diagram.pushFragment(this);
    _ref = this.children;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      item.y = current;
      item.layout();
      current = item.bottom;
    }
    this.diagram.popFragment();
    return this.bottom = this.y + current;
  };

  Alt.prototype.onDraw = function(context) {
    var textHeight;
    context.strokeStyle = Config.strokeStyle;
    context.fillStyle = Config.textFillStyle;
    textHeight = Util.measureTextHeight();
    context.beginPath();
    context.rect(this.margin, 0, this.textBoxWidth, textHeight + Config.padding);
    context.fill();
    context.stroke();
    context.fillStyle = Config.textStyle;
    return context.fillText(this.text, this.margin + Config.padding, textHeight + Config.padding / 2);
  };

  Alt.prototype.addItem = function(item) {
    item.parent = this;
    return this.add(item);
  };

  return Alt;

})(Item);

FragmentBase = (function(_super) {

  __extends(FragmentBase, _super);

  function FragmentBase(diagram, text) {
    this.diagram = diagram;
    this.text = text;
    FragmentBase.__super__.constructor.call(this);
  }

  FragmentBase.prototype.layout = function() {
    var bottom, item, _i, _len, _ref;
    bottom = Config.itemMargin;
    _ref = this.children;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      item.y = bottom + Config.itemMargin;
      item.layout();
      bottom = item.bottom;
    }
    return this.bottom = this.y + bottom + Config.itemMargin;
  };

  FragmentBase.prototype.onDraw = function(context) {
    context.strokeStyle = Config.strokeStyle;
    context.beginPath();
    context.rect(this.margin, 0, this.diagram.right - this.margin * 2, this.bottom - this.y);
    return context.stroke();
  };

  FragmentBase.prototype.addItem = function(item) {
    item.parent = this;
    return this.add(item);
  };

  return FragmentBase;

})(Item);

Guard = (function(_super) {

  __extends(Guard, _super);

  function Guard(diagram, text) {
    Guard.__super__.constructor.call(this, diagram, '[ ' + text + ' ]');
    this.textWidth = this.diagram.measureTextWidth(this.text);
  }

  Guard.prototype.onDraw = function(context) {
    var textHeight;
    this.margin = this.parent.margin;
    Guard.__super__.onDraw.call(this, context);
    context.fillStyle = Config.textFillStyle;
    textHeight = Util.measureTextHeight();
    context.fillRect(this.margin + this.parent.textBoxWidth + Config.padding, 1, this.textWidth + Config.padding, textHeight + Config.padding);
    context.fillStyle = Config.textStyle;
    return context.fillText(this.text, this.margin + this.parent.textBoxWidth + Config.padding * 2, textHeight + Config.padding / 2);
  };

  return Guard;

})(FragmentBase);

Fragment = (function(_super) {

  __extends(Fragment, _super);

  function Fragment(diagram, text) {
    Fragment.__super__.constructor.call(this, diagram, text);
    this.textWidth = this.diagram.measureTextWidth(this.text);
    this.textBoxWidth = this.textWidth + Config.padding * 2;
  }

  Fragment.prototype.layout = function() {
    this.margin = this.diagram.fragmentStack.length * Config.fragmentMargin;
    this.diagram.pushFragment(this);
    Fragment.__super__.layout.call(this);
    return this.diagram.popFragment();
  };

  Fragment.prototype.onDraw = function(context) {
    var textHeight;
    Fragment.__super__.onDraw.call(this, context);
    context.strokeStyle = Config.strokeStyle;
    context.fillStyle = Config.textFillStyle;
    textHeight = Util.measureTextHeight();
    context.beginPath();
    context.rect(this.margin, 0, this.textBoxWidth, textHeight + Config.padding);
    context.fill();
    context.stroke();
    context.fillStyle = Config.textStyle;
    return context.fillText(this.text, this.margin + Config.padding, textHeight + Config.padding / 2);
  };

  return Fragment;

})(FragmentBase);

SequenceCommandParser = (function() {

  function SequenceCommandParser(context) {
    this.diagram = new SequenceDiagram(context);
    this.factory = new CommandFactory();
  }

  SequenceCommandParser.prototype.parse = function(text) {
    var cmd, cmdText, cmdTexts, state;
    cmdTexts = text.split('\n');
    state = new State(this.factory, this.diagram, cmdTexts);
    while (state.hasNext()) {
      cmdText = state.next();
      cmd = this.factory.create(cmdText);
      if (cmd) {
        cmd.setup(cmdText);
        cmd.execute(state);
      }
    }
    return this.diagram;
  };

  return SequenceCommandParser;

})();

State = (function() {

  function State(factory, diagram, cmdTexts) {
    this.factory = factory;
    this.diagram = diagram;
    this.cmdTexts = cmdTexts;
    this.index = 0;
    this.stack = [];
    this.lines = {};
  }

  State.prototype.hasNext = function() {
    return this.index < this.cmdTexts.length;
  };

  State.prototype.next = function() {
    var cmdText;
    if (this.index < this.cmdTexts.length) {
      cmdText = this.cmdTexts[this.index];
      this.index++;
      return cmdText;
    }
  };

  State.prototype.line = function(name) {
    var line;
    line = this.lines[name];
    if (line) {
      return line;
    }
    line = new LifeLine(this.diagram, name);
    this.lines[name] = line;
    this.diagram.addLine(line);
    return line;
  };

  State.prototype.current = function() {
    if (this.stack.length === 0) {
      return this.diagram;
    }
    return this.stack[this.stack.length - 1];
  };

  return State;

})();

CommandFactory = (function() {

  function CommandFactory() {
    this.cmds = [];
    this.cmds.push(new AltCommand);
    this.cmds.push(new OptionCommand);
    this.cmds.push(new ElseCommand);
    this.cmds.push(new EndCommand);
    this.cmds.push(new NoteCommand);
    this.cmds.push(new MessageCommand);
    this.cmds.push(new ExecutionCommand);
  }

  CommandFactory.prototype.create = function(cmdText) {
    var cmd, _i, _len, _ref;
    _ref = this.cmds;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      cmd = _ref[_i];
      if (cmd.match(cmdText)) {
        return cmd;
      }
    }
  };

  return CommandFactory;

})();

Command = (function() {

  function Command() {}

  Command.prototype.setup = function(text) {
    var index, result, value, _i, _len, _results;
    result = this.match(text);
    _results = [];
    for (index = _i = 0, _len = result.length; _i < _len; index = ++_i) {
      value = result[index];
      if (value) {
        value = value.trim();
      }
      if (0 < index) {
        _results.push(this[this.names[index - 1]] = value);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  Command.prototype.match = function(text) {
    return text.match(this.reg);
  };

  return Command;

})();

MessageCommand = (function(_super) {

  __extends(MessageCommand, _super);

  function MessageCommand() {
    return MessageCommand.__super__.constructor.apply(this, arguments);
  }

  MessageCommand.prototype.reg = /^\s*?([^\]>-]+)(\])?->([^\[:]+)(\[)?(?::(.*))?$/;

  MessageCommand.prototype.names = ["fromName", "isReply", "toName", "isSync", "text"];

  MessageCommand.prototype.execute = function(state) {
    var from, message, to;
    from = state.line(this.fromName);
    to = state.line(this.toName);
    if (this.isReply) {
      message = new ReplyMessage(state.diagram, this.text, from, to);
    } else if (this.isSync) {
      message = new SyncMessage(state.diagram, this.text, from, to);
    } else {
      message = new Message(state.diagram, this.text, from, to);
    }
    return state.current().addItem(message);
  };

  return MessageCommand;

})(Command);

NoteCommand = (function(_super) {

  __extends(NoteCommand, _super);

  function NoteCommand() {
    return NoteCommand.__super__.constructor.apply(this, arguments);
  }

  NoteCommand.prototype.reg = /^\s*(left|right|note|comment)@([^\:]+):(.*)$/i;

  NoteCommand.prototype.names = ["position", "lineName", "text"];

  NoteCommand.prototype.execute = function(state) {
    return state.current().addItem(new Note(state.diagram, this.text, state.line(this.lineName), this.position === "left"));
  };

  return NoteCommand;

})(Command);

ExecutionCommand = (function(_super) {

  __extends(ExecutionCommand, _super);

  function ExecutionCommand() {
    return ExecutionCommand.__super__.constructor.apply(this, arguments);
  }

  ExecutionCommand.prototype.reg = /^([^\[\]]+)(\[|\])$/;

  ExecutionCommand.prototype.names = ["lineName", "last"];

  ExecutionCommand.prototype.execute = function(state) {
    var item;
    if (this.last === '[') {
      item = new ExecutionStart(state.line(this.lineName));
    } else {
      item = new ExecutionEnd(state.line(this.lineName));
    }
    return state.current().addItem(item);
  };

  return ExecutionCommand;

})(Command);

OptionCommand = (function(_super) {

  __extends(OptionCommand, _super);

  function OptionCommand() {
    return OptionCommand.__super__.constructor.apply(this, arguments);
  }

  OptionCommand.prototype.reg = /^\s*(assert|break|consider|critical|ignore|loop|neg|opt|par|seq|strict)(?::(.*))?$/i;

  OptionCommand.prototype.names = ["type", "text"];

  OptionCommand.prototype.execute = function(state) {
    var frag;
    if (this.text) {
      frag = new Fragment(state.diagram, this.type + " [" + this.text + "]");
    } else {
      frag = new Fragment(state.diagram, this.type);
    }
    state.current().addItem(frag);
    return state.stack.push(frag);
  };

  return OptionCommand;

})(Command);

EndCommand = (function(_super) {

  __extends(EndCommand, _super);

  function EndCommand() {
    return EndCommand.__super__.constructor.apply(this, arguments);
  }

  EndCommand.prototype.reg = /^\s*end\s*$/i;

  EndCommand.prototype.names = [];

  EndCommand.prototype.execute = function(state) {
    return state.stack.pop();
  };

  return EndCommand;

})(Command);

AltCommand = (function(_super) {

  __extends(AltCommand, _super);

  function AltCommand() {
    return AltCommand.__super__.constructor.apply(this, arguments);
  }

  AltCommand.prototype.reg = /^\s*alt(?:\:(.*))?$/i;

  AltCommand.prototype.names = ["text"];

  AltCommand.prototype.execute = function(state) {
    var alt, guard;
    alt = new Alt(state.diagram, "alt");
    state.current().addItem(alt);
    guard = new Guard(state.diagram, this.text);
    state.stack.push(guard);
    return alt.addItem(guard);
  };

  return AltCommand;

})(Command);

ElseCommand = (function(_super) {

  __extends(ElseCommand, _super);

  function ElseCommand() {
    return ElseCommand.__super__.constructor.apply(this, arguments);
  }

  ElseCommand.prototype.reg = /^\s*else(?:\:(.*))?$/i;

  ElseCommand.prototype.names = ["text"];

  ElseCommand.prototype.execute = function(state) {
    var guard;
    guard = new Guard(state.diagram, this.text);
    state.current().parent.addItem(guard);
    state.stack.pop();
    return state.stack.push(guard);
  };

  return ElseCommand;

})(Command);
